# Generated by Django 3.0 on 2024-02-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('alert_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=20)),
                ('animal_image', models.ImageField(upload_to='')),
                ('animal_description', models.CharField(max_length=20)),
                ('safety_tips', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Forest_Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Forest_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('FOREST_DIVISION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Forest_Division')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('FOREST_STATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Forest_Station')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Preserved_Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANIMAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Forest_Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_image', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('reply', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('FOREST_OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Forest_Officer')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='FOREST_DIVISION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Forest_Division'),
        ),
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('FOREST_OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Forest_Officer')),
                ('FOREST_STATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Forest_Station')),
            ],
        ),
    ]
